use super::gitlab_project_components::{Group, Namespace, Owner, Statistics, Links};

#[derive(Deserialize, Debug)]
pub struct GitlabProject {
    id: u32,
    description: Option<String>,
    default_branch: String,
    visibility: String,
    ssh_url_to_repo: String,
    http_url_to_repo: String,
    web_url: String,
    readme_url: String,
    tag_list: Vec<String>,
    owner: Owner,
    name: String,
    name_with_namespace: String,
    path: String,
    path_with_namespace: String,
    issues_enabled: bool,
    open_issues_count: i32,
    merge_requests_enabled: bool,
    jobs_enabled: bool,
    wiki_enabled: bool,
    snippets_enabled: bool,
    can_create_merge_request_in: bool,
    resolve_outdated_diff_discussions: bool,
    container_registry_enabled: bool,
    created_at: String,
    last_activity_at: String,
    creator_id: i32,
    namespace: Namespace,
    import_status: String,
    archived: bool,
    avatar_url: String,
    shared_runners_enabled: bool,
    forks_count: i32,
    star_count: i32,
    runners_token: String,
    ci_default_git_depth: i32,
    ci_forward_deployment_enabled: bool,
    public_jobs: bool,
    shared_with_groups: Vec<Group>,
    only_allow_merge_if_pipeline_succeeds: bool,
    allow_merge_on_skipped_pipeline: bool,
    restrict_user_defined_variables: bool,
    only_allow_merge_if_all_discussions_are_resolved: bool,
    remove_source_branch_after_merge: bool,
    request_access_enabled: bool,
    merge_method: String,
    autoclose_referenced_issues: bool,
    suggestion_commit_message: Option<String>,
    marked_for_deletion_at: String, // Deprecated and will be removed in API v5 in favor of marked_for_deletion_on
    marked_for_deletion_on: String,
    statistics: Statistics,
    container_registry_image_prefix: String,
    _links: Links,
}
